// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPYppgSyxXGnpKvw3Bl60Eh_Pp1hgu_A',
    appId: '1:509935924102:web:8b4803faf49e82573eb207',
    messagingSenderId: '509935924102',
    projectId: 'swaptry2',
    authDomain: 'swaptry2.firebaseapp.com',
    storageBucket: 'swaptry2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPHjNV5ffhs4xg6GkTr1EKYOiZLMbKKrM',
    appId: '1:509935924102:android:0c90ab4a76788bf93eb207',
    messagingSenderId: '509935924102',
    projectId: 'swaptry2',
    storageBucket: 'swaptry2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD95IFsMOcjEvU2Dnb8lqHitenhT_AStnY',
    appId: '1:509935924102:ios:44c62206c81d84373eb207',
    messagingSenderId: '509935924102',
    projectId: 'swaptry2',
    storageBucket: 'swaptry2.appspot.com',
    iosClientId: '509935924102-s74jqu5u94241udpiftvkkjupsn0vahk.apps.googleusercontent.com',
    iosBundleId: 'com.example.swaptry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD95IFsMOcjEvU2Dnb8lqHitenhT_AStnY',
    appId: '1:509935924102:ios:44c62206c81d84373eb207',
    messagingSenderId: '509935924102',
    projectId: 'swaptry2',
    storageBucket: 'swaptry2.appspot.com',
    iosClientId: '509935924102-s74jqu5u94241udpiftvkkjupsn0vahk.apps.googleusercontent.com',
    iosBundleId: 'com.example.swaptry',
  );
}
